version: '3.8'

services:
  web:
    build:
      context: .  # Path on the host where Dockerfile is located
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
     
